<meta charset="UTF-8"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta content='kuhinje' name='keywords' />
<meta name="robots" content="follow, all, index" />
<link href='{{site.url}}/css/reset.css' rel='stylesheet' type='text/css' />
<link href='{{site.url}}/css/text.css' rel='stylesheet' type='text/css' />
<link href='{{site.url}}/css/960_12_col.css' rel='stylesheet' type='text/css' />
<link href='{{site.url}}/css/styles.css' rel='stylesheet' type='text/css' />
<link href='{{site.url}}/css/goog.css' rel='stylesheet' type='text/css' />
